version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: hank
  coins:
  - 1000000token
  - 2000000000stake
  address: archive1xewtex2nz6e2vvuqeg9cfj862mreahpfcmly0p
faucet:
  name: bob
  coins:
  - 5000000000token
  - 1000000000stake
  host: 0.0.0.0:4500
client:
  typescript:
    path: vue/src/generated
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  chain_id: casper-1
validators:
- name: alice
  bonded: 100000000stake
  app:
    minimum-gas-prices: 0.000001token
