// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: archive/identity/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterIssuer struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MoreInfoUri string `protobuf:"bytes,3,opt,name=more_info_uri,json=moreInfoUri,proto3" json:"more_info_uri,omitempty"`
	Cost        uint64 `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
}

func (m *MsgRegisterIssuer) Reset()         { *m = MsgRegisterIssuer{} }
func (m *MsgRegisterIssuer) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterIssuer) ProtoMessage()    {}
func (*MsgRegisterIssuer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5475f4c184c4e6, []int{0}
}
func (m *MsgRegisterIssuer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterIssuer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterIssuer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterIssuer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterIssuer.Merge(m, src)
}
func (m *MsgRegisterIssuer) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterIssuer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterIssuer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterIssuer proto.InternalMessageInfo

func (m *MsgRegisterIssuer) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRegisterIssuer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgRegisterIssuer) GetMoreInfoUri() string {
	if m != nil {
		return m.MoreInfoUri
	}
	return ""
}

func (m *MsgRegisterIssuer) GetCost() uint64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type MsgRegisterIssuerResponse struct {
}

func (m *MsgRegisterIssuerResponse) Reset()         { *m = MsgRegisterIssuerResponse{} }
func (m *MsgRegisterIssuerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterIssuerResponse) ProtoMessage()    {}
func (*MsgRegisterIssuerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5475f4c184c4e6, []int{1}
}
func (m *MsgRegisterIssuerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterIssuerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterIssuerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterIssuerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterIssuerResponse.Merge(m, src)
}
func (m *MsgRegisterIssuerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterIssuerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterIssuerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterIssuerResponse proto.InternalMessageInfo

type MsgIssueCertificate struct {
	Creator           string       `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Recipient         string       `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Salt              string       `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	MetadataSchemaUri string       `protobuf:"bytes,4,opt,name=metadata_schema_uri,json=metadataSchemaUri,proto3" json:"metadata_schema_uri,omitempty"`
	Hashes            []*HashEntry `protobuf:"bytes,5,rep,name=hashes,proto3" json:"hashes,omitempty"`
}

func (m *MsgIssueCertificate) Reset()         { *m = MsgIssueCertificate{} }
func (m *MsgIssueCertificate) String() string { return proto.CompactTextString(m) }
func (*MsgIssueCertificate) ProtoMessage()    {}
func (*MsgIssueCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5475f4c184c4e6, []int{2}
}
func (m *MsgIssueCertificate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIssueCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIssueCertificate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIssueCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIssueCertificate.Merge(m, src)
}
func (m *MsgIssueCertificate) XXX_Size() int {
	return m.Size()
}
func (m *MsgIssueCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIssueCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIssueCertificate proto.InternalMessageInfo

func (m *MsgIssueCertificate) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgIssueCertificate) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgIssueCertificate) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *MsgIssueCertificate) GetMetadataSchemaUri() string {
	if m != nil {
		return m.MetadataSchemaUri
	}
	return ""
}

func (m *MsgIssueCertificate) GetHashes() []*HashEntry {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type MsgIssueCertificateResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgIssueCertificateResponse) Reset()         { *m = MsgIssueCertificateResponse{} }
func (m *MsgIssueCertificateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgIssueCertificateResponse) ProtoMessage()    {}
func (*MsgIssueCertificateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5475f4c184c4e6, []int{3}
}
func (m *MsgIssueCertificateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIssueCertificateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIssueCertificateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIssueCertificateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIssueCertificateResponse.Merge(m, src)
}
func (m *MsgIssueCertificateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgIssueCertificateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIssueCertificateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIssueCertificateResponse proto.InternalMessageInfo

func (m *MsgIssueCertificateResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgAcceptIdentity struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgAcceptIdentity) Reset()         { *m = MsgAcceptIdentity{} }
func (m *MsgAcceptIdentity) String() string { return proto.CompactTextString(m) }
func (*MsgAcceptIdentity) ProtoMessage()    {}
func (*MsgAcceptIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5475f4c184c4e6, []int{4}
}
func (m *MsgAcceptIdentity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAcceptIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAcceptIdentity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAcceptIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAcceptIdentity.Merge(m, src)
}
func (m *MsgAcceptIdentity) XXX_Size() int {
	return m.Size()
}
func (m *MsgAcceptIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAcceptIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAcceptIdentity proto.InternalMessageInfo

func (m *MsgAcceptIdentity) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAcceptIdentity) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgAcceptIdentityResponse struct {
}

func (m *MsgAcceptIdentityResponse) Reset()         { *m = MsgAcceptIdentityResponse{} }
func (m *MsgAcceptIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAcceptIdentityResponse) ProtoMessage()    {}
func (*MsgAcceptIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5475f4c184c4e6, []int{5}
}
func (m *MsgAcceptIdentityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAcceptIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAcceptIdentityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAcceptIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAcceptIdentityResponse.Merge(m, src)
}
func (m *MsgAcceptIdentityResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAcceptIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAcceptIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAcceptIdentityResponse proto.InternalMessageInfo

type MsgRejectIdentity struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgRejectIdentity) Reset()         { *m = MsgRejectIdentity{} }
func (m *MsgRejectIdentity) String() string { return proto.CompactTextString(m) }
func (*MsgRejectIdentity) ProtoMessage()    {}
func (*MsgRejectIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5475f4c184c4e6, []int{6}
}
func (m *MsgRejectIdentity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRejectIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRejectIdentity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRejectIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRejectIdentity.Merge(m, src)
}
func (m *MsgRejectIdentity) XXX_Size() int {
	return m.Size()
}
func (m *MsgRejectIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRejectIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRejectIdentity proto.InternalMessageInfo

func (m *MsgRejectIdentity) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRejectIdentity) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgRejectIdentityResponse struct {
}

func (m *MsgRejectIdentityResponse) Reset()         { *m = MsgRejectIdentityResponse{} }
func (m *MsgRejectIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRejectIdentityResponse) ProtoMessage()    {}
func (*MsgRejectIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5475f4c184c4e6, []int{7}
}
func (m *MsgRejectIdentityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRejectIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRejectIdentityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRejectIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRejectIdentityResponse.Merge(m, src)
}
func (m *MsgRejectIdentityResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRejectIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRejectIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRejectIdentityResponse proto.InternalMessageInfo

type MsgRevokeIdentity struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Member  string `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
}

func (m *MsgRevokeIdentity) Reset()         { *m = MsgRevokeIdentity{} }
func (m *MsgRevokeIdentity) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeIdentity) ProtoMessage()    {}
func (*MsgRevokeIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5475f4c184c4e6, []int{8}
}
func (m *MsgRevokeIdentity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevokeIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevokeIdentity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevokeIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeIdentity.Merge(m, src)
}
func (m *MsgRevokeIdentity) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevokeIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeIdentity proto.InternalMessageInfo

func (m *MsgRevokeIdentity) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRevokeIdentity) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgRevokeIdentity) GetMember() string {
	if m != nil {
		return m.Member
	}
	return ""
}

type MsgRevokeIdentityResponse struct {
}

func (m *MsgRevokeIdentityResponse) Reset()         { *m = MsgRevokeIdentityResponse{} }
func (m *MsgRevokeIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeIdentityResponse) ProtoMessage()    {}
func (*MsgRevokeIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad5475f4c184c4e6, []int{9}
}
func (m *MsgRevokeIdentityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevokeIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevokeIdentityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevokeIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeIdentityResponse.Merge(m, src)
}
func (m *MsgRevokeIdentityResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevokeIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeIdentityResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterIssuer)(nil), "archive.identity.MsgRegisterIssuer")
	proto.RegisterType((*MsgRegisterIssuerResponse)(nil), "archive.identity.MsgRegisterIssuerResponse")
	proto.RegisterType((*MsgIssueCertificate)(nil), "archive.identity.MsgIssueCertificate")
	proto.RegisterType((*MsgIssueCertificateResponse)(nil), "archive.identity.MsgIssueCertificateResponse")
	proto.RegisterType((*MsgAcceptIdentity)(nil), "archive.identity.MsgAcceptIdentity")
	proto.RegisterType((*MsgAcceptIdentityResponse)(nil), "archive.identity.MsgAcceptIdentityResponse")
	proto.RegisterType((*MsgRejectIdentity)(nil), "archive.identity.MsgRejectIdentity")
	proto.RegisterType((*MsgRejectIdentityResponse)(nil), "archive.identity.MsgRejectIdentityResponse")
	proto.RegisterType((*MsgRevokeIdentity)(nil), "archive.identity.MsgRevokeIdentity")
	proto.RegisterType((*MsgRevokeIdentityResponse)(nil), "archive.identity.MsgRevokeIdentityResponse")
}

func init() { proto.RegisterFile("archive/identity/tx.proto", fileDescriptor_ad5475f4c184c4e6) }

var fileDescriptor_ad5475f4c184c4e6 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0x1a, 0x31,
	0x10, 0x65, 0x81, 0x52, 0xc5, 0xa8, 0x34, 0x38, 0x6d, 0xb5, 0x81, 0x6a, 0x83, 0xb6, 0xaa, 0x84,
	0x54, 0x05, 0x24, 0x38, 0xe7, 0xd0, 0x54, 0x91, 0xca, 0x81, 0xcb, 0x56, 0xb9, 0xf4, 0x82, 0x8c,
	0x19, 0x76, 0xdd, 0x76, 0xd7, 0xc8, 0x76, 0xa2, 0xf0, 0x17, 0x7a, 0xea, 0xcf, 0xea, 0x31, 0xc7,
	0x5e, 0x1a, 0x55, 0xf0, 0x43, 0x5a, 0xe1, 0x5d, 0x16, 0xf6, 0x2b, 0x4a, 0x73, 0xb3, 0x3d, 0x6f,
	0xde, 0xcc, 0x9b, 0x79, 0x32, 0x3a, 0x26, 0x82, 0x7a, 0xec, 0x1a, 0xfa, 0x6c, 0x06, 0x81, 0x62,
	0x6a, 0xd9, 0x57, 0x37, 0xbd, 0x85, 0xe0, 0x8a, 0xe3, 0xc3, 0x28, 0xd4, 0xdb, 0x86, 0x5a, 0x2f,
	0x5c, 0xee, 0x72, 0x1d, 0xec, 0x6f, 0x4e, 0x21, 0xae, 0x65, 0x67, 0x28, 0x28, 0x08, 0xc5, 0xe6,
	0x8c, 0x12, 0x05, 0x21, 0xc6, 0xfe, 0x6e, 0xa0, 0xe6, 0x58, 0xba, 0x0e, 0xb8, 0x4c, 0x2a, 0x10,
	0x23, 0x29, 0xaf, 0x40, 0x60, 0x13, 0x3d, 0xa5, 0x02, 0x88, 0xe2, 0xc2, 0x34, 0x3a, 0x46, 0xf7,
	0xc0, 0xd9, 0x5e, 0x31, 0x46, 0xd5, 0x80, 0xf8, 0x60, 0x96, 0xf5, 0xb3, 0x3e, 0xe3, 0x21, 0x7a,
	0xe6, 0x73, 0x01, 0x13, 0x16, 0xcc, 0xf9, 0xe4, 0x4a, 0x30, 0xb3, 0xb2, 0x09, 0x9e, 0x3f, 0x5f,
	0xdd, 0x9d, 0xd4, 0xc7, 0x5c, 0xc0, 0x28, 0x98, 0xf3, 0x4b, 0xc1, 0x9c, 0xba, 0xbf, 0xbb, 0x6c,
	0x88, 0x28, 0x97, 0xca, 0xac, 0x76, 0x8c, 0x6e, 0xd5, 0xd1, 0x67, 0xbb, 0x8d, 0x8e, 0x33, 0xbd,
	0x38, 0x20, 0x17, 0x3c, 0x90, 0x60, 0xff, 0x36, 0xd0, 0xd1, 0x58, 0xba, 0xfa, 0xf5, 0xc3, 0x4e,
	0xc7, 0x3d, 0xbd, 0xbe, 0x46, 0x07, 0x02, 0x28, 0x5b, 0x30, 0x08, 0x54, 0xd4, 0xf0, 0xee, 0x61,
	0xd3, 0x80, 0x24, 0xdf, 0x54, 0xd8, 0xac, 0xa3, 0xcf, 0xf8, 0x02, 0x1d, 0xf9, 0xa0, 0xc8, 0x8c,
	0x28, 0x32, 0x91, 0xd4, 0x03, 0x9f, 0x68, 0x3d, 0x55, 0xad, 0xe7, 0xe5, 0xea, 0xee, 0xa4, 0x39,
	0x8e, 0xc2, 0x9f, 0x74, 0x74, 0xa3, 0xaa, 0xe9, 0xa7, 0x9f, 0xf0, 0x10, 0xd5, 0x3c, 0x22, 0x3d,
	0x90, 0xe6, 0x93, 0x4e, 0xa5, 0x5b, 0x1f, 0xb4, 0x7b, 0xe9, 0x8d, 0xf5, 0x3e, 0x12, 0xe9, 0x5d,
	0x04, 0x4a, 0x2c, 0x9d, 0x08, 0x6a, 0x9f, 0xa2, 0x76, 0x8e, 0xbc, 0xad, 0x7c, 0xdc, 0x40, 0x65,
	0x36, 0xd3, 0x0a, 0xab, 0x4e, 0x99, 0xcd, 0xec, 0x33, 0xbd, 0xb7, 0xf7, 0x94, 0xc2, 0x42, 0x8d,
	0x22, 0xd6, 0x7b, 0x66, 0x11, 0xa6, 0x97, 0xe3, 0xf4, 0x70, 0xd4, 0xc9, 0xf4, 0x78, 0xd4, 0x67,
	0x91, 0x27, 0xbe, 0x00, 0x7d, 0x3c, 0x77, 0x32, 0x3d, 0xe6, 0xbe, 0x8c, 0xb8, 0xaf, 0xf9, 0x57,
	0xf8, 0x7f, 0x6e, 0xfc, 0x0a, 0xd5, 0x7c, 0xf0, 0xa7, 0x20, 0xa2, 0xbd, 0x45, 0xb7, 0xb8, 0xe6,
	0x3e, 0xed, 0xb6, 0xe6, 0xe0, 0x6f, 0x05, 0x55, 0xc6, 0xd2, 0xc5, 0x53, 0xd4, 0x48, 0x19, 0xfd,
	0x4d, 0x76, 0x33, 0x19, 0x07, 0xb6, 0xde, 0x3d, 0x00, 0x14, 0xef, 0xc9, 0x43, 0x87, 0x19, 0x8b,
	0xbe, 0xcd, 0x25, 0x48, 0xc3, 0x5a, 0xa7, 0x0f, 0x82, 0xc5, 0x95, 0xa6, 0xa8, 0x91, 0x5a, 0x7f,
	0xbe, 0x9a, 0x24, 0xa8, 0x40, 0x4d, 0xbe, 0x13, 0xc2, 0x89, 0x25, 0x6c, 0x50, 0x34, 0xb1, 0x7d,
	0x50, 0xe1, 0xc4, 0xf2, 0x1c, 0x11, 0xd6, 0x48, 0xd8, 0xa1, 0xa8, 0xc6, 0x3e, 0xa8, 0xb0, 0x46,
	0x9e, 0x03, 0xce, 0x07, 0x3f, 0x57, 0x96, 0x71, 0xbb, 0xb2, 0x8c, 0x3f, 0x2b, 0xcb, 0xf8, 0xb1,
	0xb6, 0x4a, 0xb7, 0x6b, 0xab, 0xf4, 0x6b, 0x6d, 0x95, 0x3e, 0x9b, 0xdb, 0x4f, 0xf2, 0x66, 0xef,
	0xa7, 0x5d, 0x2e, 0x40, 0x4e, 0x6b, 0xfa, 0x87, 0x1c, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xb2,
	0x35, 0x3f, 0xcb, 0x8a, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RegisterIssuer(ctx context.Context, in *MsgRegisterIssuer, opts ...grpc.CallOption) (*MsgRegisterIssuerResponse, error)
	IssueCertificate(ctx context.Context, in *MsgIssueCertificate, opts ...grpc.CallOption) (*MsgIssueCertificateResponse, error)
	AcceptIdentity(ctx context.Context, in *MsgAcceptIdentity, opts ...grpc.CallOption) (*MsgAcceptIdentityResponse, error)
	RejectIdentity(ctx context.Context, in *MsgRejectIdentity, opts ...grpc.CallOption) (*MsgRejectIdentityResponse, error)
	RevokeIdentity(ctx context.Context, in *MsgRevokeIdentity, opts ...grpc.CallOption) (*MsgRevokeIdentityResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterIssuer(ctx context.Context, in *MsgRegisterIssuer, opts ...grpc.CallOption) (*MsgRegisterIssuerResponse, error) {
	out := new(MsgRegisterIssuerResponse)
	err := c.cc.Invoke(ctx, "/archive.identity.Msg/RegisterIssuer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) IssueCertificate(ctx context.Context, in *MsgIssueCertificate, opts ...grpc.CallOption) (*MsgIssueCertificateResponse, error) {
	out := new(MsgIssueCertificateResponse)
	err := c.cc.Invoke(ctx, "/archive.identity.Msg/IssueCertificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AcceptIdentity(ctx context.Context, in *MsgAcceptIdentity, opts ...grpc.CallOption) (*MsgAcceptIdentityResponse, error) {
	out := new(MsgAcceptIdentityResponse)
	err := c.cc.Invoke(ctx, "/archive.identity.Msg/AcceptIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RejectIdentity(ctx context.Context, in *MsgRejectIdentity, opts ...grpc.CallOption) (*MsgRejectIdentityResponse, error) {
	out := new(MsgRejectIdentityResponse)
	err := c.cc.Invoke(ctx, "/archive.identity.Msg/RejectIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeIdentity(ctx context.Context, in *MsgRevokeIdentity, opts ...grpc.CallOption) (*MsgRevokeIdentityResponse, error) {
	out := new(MsgRevokeIdentityResponse)
	err := c.cc.Invoke(ctx, "/archive.identity.Msg/RevokeIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RegisterIssuer(context.Context, *MsgRegisterIssuer) (*MsgRegisterIssuerResponse, error)
	IssueCertificate(context.Context, *MsgIssueCertificate) (*MsgIssueCertificateResponse, error)
	AcceptIdentity(context.Context, *MsgAcceptIdentity) (*MsgAcceptIdentityResponse, error)
	RejectIdentity(context.Context, *MsgRejectIdentity) (*MsgRejectIdentityResponse, error)
	RevokeIdentity(context.Context, *MsgRevokeIdentity) (*MsgRevokeIdentityResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterIssuer(ctx context.Context, req *MsgRegisterIssuer) (*MsgRegisterIssuerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterIssuer not implemented")
}
func (*UnimplementedMsgServer) IssueCertificate(ctx context.Context, req *MsgIssueCertificate) (*MsgIssueCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueCertificate not implemented")
}
func (*UnimplementedMsgServer) AcceptIdentity(ctx context.Context, req *MsgAcceptIdentity) (*MsgAcceptIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptIdentity not implemented")
}
func (*UnimplementedMsgServer) RejectIdentity(ctx context.Context, req *MsgRejectIdentity) (*MsgRejectIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectIdentity not implemented")
}
func (*UnimplementedMsgServer) RevokeIdentity(ctx context.Context, req *MsgRevokeIdentity) (*MsgRevokeIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeIdentity not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterIssuer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterIssuer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterIssuer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/archive.identity.Msg/RegisterIssuer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterIssuer(ctx, req.(*MsgRegisterIssuer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_IssueCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgIssueCertificate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).IssueCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/archive.identity.Msg/IssueCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).IssueCertificate(ctx, req.(*MsgIssueCertificate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AcceptIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAcceptIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AcceptIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/archive.identity.Msg/AcceptIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AcceptIdentity(ctx, req.(*MsgAcceptIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RejectIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRejectIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RejectIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/archive.identity.Msg/RejectIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RejectIdentity(ctx, req.(*MsgRejectIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/archive.identity.Msg/RevokeIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeIdentity(ctx, req.(*MsgRevokeIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "archive.identity.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterIssuer",
			Handler:    _Msg_RegisterIssuer_Handler,
		},
		{
			MethodName: "IssueCertificate",
			Handler:    _Msg_IssueCertificate_Handler,
		},
		{
			MethodName: "AcceptIdentity",
			Handler:    _Msg_AcceptIdentity_Handler,
		},
		{
			MethodName: "RejectIdentity",
			Handler:    _Msg_RejectIdentity_Handler,
		},
		{
			MethodName: "RevokeIdentity",
			Handler:    _Msg_RevokeIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "archive/identity/tx.proto",
}

func (m *MsgRegisterIssuer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterIssuer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterIssuer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Cost != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Cost))
		i--
		dAtA[i] = 0x20
	}
	if len(m.MoreInfoUri) > 0 {
		i -= len(m.MoreInfoUri)
		copy(dAtA[i:], m.MoreInfoUri)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MoreInfoUri)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterIssuerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterIssuerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterIssuerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgIssueCertificate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIssueCertificate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIssueCertificate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hashes) > 0 {
		for iNdEx := len(m.Hashes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Hashes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.MetadataSchemaUri) > 0 {
		i -= len(m.MetadataSchemaUri)
		copy(dAtA[i:], m.MetadataSchemaUri)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MetadataSchemaUri)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Salt) > 0 {
		i -= len(m.Salt)
		copy(dAtA[i:], m.Salt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Salt)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgIssueCertificateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIssueCertificateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIssueCertificateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgAcceptIdentity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAcceptIdentity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAcceptIdentity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAcceptIdentityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAcceptIdentityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAcceptIdentityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRejectIdentity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRejectIdentity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRejectIdentity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRejectIdentityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRejectIdentityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRejectIdentityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRevokeIdentity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevokeIdentity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevokeIdentity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Member) > 0 {
		i -= len(m.Member)
		copy(dAtA[i:], m.Member)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Member)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRevokeIdentityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevokeIdentityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevokeIdentityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterIssuer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MoreInfoUri)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Cost != 0 {
		n += 1 + sovTx(uint64(m.Cost))
	}
	return n
}

func (m *MsgRegisterIssuerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgIssueCertificate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Salt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MetadataSchemaUri)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Hashes) > 0 {
		for _, e := range m.Hashes {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgIssueCertificateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgAcceptIdentity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgAcceptIdentityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRejectIdentity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgRejectIdentityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRevokeIdentity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.Member)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRevokeIdentityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterIssuer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterIssuer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterIssuer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MoreInfoUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MoreInfoUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cost", wireType)
			}
			m.Cost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cost |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterIssuerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterIssuerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterIssuerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIssueCertificate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIssueCertificate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIssueCertificate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Salt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Salt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataSchemaUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataSchemaUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hashes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hashes = append(m.Hashes, &HashEntry{})
			if err := m.Hashes[len(m.Hashes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIssueCertificateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIssueCertificateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIssueCertificateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAcceptIdentity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAcceptIdentity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAcceptIdentity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAcceptIdentityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAcceptIdentityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAcceptIdentityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRejectIdentity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRejectIdentity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRejectIdentity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRejectIdentityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRejectIdentityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRejectIdentityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevokeIdentity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevokeIdentity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevokeIdentity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Member", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Member = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevokeIdentityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevokeIdentityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevokeIdentityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
